insert into content (content_type, name, id) values (1, 'Introduction to java', 2)
insert into video_content (description, resource_url, id) values ('This video will introduce the basic concepts of java','resourceUrl', 2)
insert into content (content_type, name, id) values (0, 'Hello CodeBlurb', 1)
insert into coding_content (coding_content_type, description, id) values (1, 'This is a hello world example', 1)
insert into test_case (example_test_case, expected_output, input, id) values (true, 'Hello CodeBlurb!', '', 1)
insert into content (content_type, name, id) values (2, 'Java hello world quiz', 3)
insert into quiz_content (id) values (3)
insert into quiz_question (question, quiz_id, solution_index, id) values ('How to print hello world?', 3, 1, 1)
insert into content_bundle (title, id) values ('bundle1', 1)
insert into content_bundle (title, id) values ('bundle2', 2)
insert into coding_content_code_skeleton (coding_content_id, code_skeleton) values (1, 'public class CodeSolution {')
insert into coding_content_code_skeleton (coding_content_id, code_skeleton) values (1, 'public static void main(String[] args) {')
insert into coding_content_code_skeleton (coding_content_id, code_skeleton) values (1, '}')
insert into coding_content_code_skeleton (coding_content_id, code_skeleton) values (1, '}')
insert into coding_content_code_snippets (coding_content_id, code_snippets) values (1, 'System.out.println("Hello CodeBlurb!");')
update test_case set coding_content_id=1 where id=1
insert into quiz_question_answers (quiz_question_id, answers) values (1, 'hello world')
insert into quiz_question_answers (quiz_question_id, answers) values (1, 'System.out.println("hello world");')
insert into quiz_question_answers (quiz_question_id, answers) values (1, 'console.log("hello world")')
insert into content_included_in_bundles (content_bundle_id, content_id) values (1, 1)
insert into content_included_in_bundles (content_bundle_id, content_id) values (1, 3)
insert into content_included_in_bundles (content_bundle_id, content_id) values (2, 2)

