name: codeblurb
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

    # L10n
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  cupertino_icons: ^1.0.2
  auto_route: ^4.2.1
  modal_bottom_sheet: ^2.1.0
  flutter_svg: ^1.1.1+1
  riverpod: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  auto_route_generator: ^4.2.0
  build_runner: ^2.1.11
  flutter_gen_runner: ^4.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_gen:
  output: lib/generated/assets
  line_length: 80

  integrations:
    flutter_svg: true

flutter_intl:
  enabled: true
