name: codeblurb
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

    # L10n
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  cupertino_icons: ^1.0.2
  auto_route: ^4.2.1
  modal_bottom_sheet: ^2.1.0
  flutter_svg: ^1.1.1+1
  firebase_core: ^1.22.0
  firebase_crashlytics: ^2.8.10
  firebase_remote_config: ^2.0.17
  firebase_analytics: ^9.3.4
  shared_preferences: ^2.0.15
  flutter_riverpod: ^2.0.0-dev.9
  cached_network_image: ^3.2.2
  json_annotation: ^4.6.0
  freezed_annotation: ^2.1.0
  auto_size_text: ^3.0.0
  dio: ^4.0.6
  google_fonts: ^3.0.1
  pretty_dio_logger: ^1.2.0-beta-1
  flutter_rating_bar: ^4.0.1
  flutter_syntax_view: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  auto_route_generator: ^4.2.0
  build_runner: ^2.1.11
  flutter_gen_runner: ^4.3.0
  freezed: ^2.1.0+1
  flutter_gen: ^4.3.0
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_gen:
  output: lib/generated/assets
  line_length: 80

  integrations:
    flutter_svg: true

flutter_intl:
  enabled: true
