/**
 * CodeBlurb API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TestCaseOutcomeResponse } from './testCaseOutcomeResponse';

export interface CodeSolutionResponse { 
    results?: Array<TestCaseOutcomeResponse>;
    overallResult?: CodeSolutionResponse.OverallResultEnum;
}
export namespace CodeSolutionResponse {
    export type OverallResultEnum = 'ALL_PASSED' | 'TESTCASES_FAILED';
    export const OverallResultEnum = {
        ALLPASSED: 'ALL_PASSED' as OverallResultEnum,
        TESTCASESFAILED: 'TESTCASES_FAILED' as OverallResultEnum
    };
}