/**
 * CodeBlurb API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ContentResponse } from './contentResponse';
import { TestCaseResponse } from './testCaseResponse';

export interface CodingContentResponse extends ContentResponse { 
    id?: number;
    contentType?: CodingContentResponse.ContentTypeEnum;
    description?: string;
    codeSkeleton?: Array<string>;
    codeSnippets?: Array<string>;
    testCases?: Array<TestCaseResponse>;
    codingContentType?: CodingContentResponse.CodingContentTypeEnum;
}
export namespace CodingContentResponse {
    export type ContentTypeEnum = 'CODING';
    export const ContentTypeEnum = {
        CODING: 'CODING' as ContentTypeEnum
    };
    export type CodingContentTypeEnum = 'SCRATCH' | 'DRAG_AND_DROP' | 'FILL_THE_GAP';
    export const CodingContentTypeEnum = {
        SCRATCH: 'SCRATCH' as CodingContentTypeEnum,
        DRAGANDDROP: 'DRAG_AND_DROP' as CodingContentTypeEnum,
        FILLTHEGAP: 'FILL_THE_GAP' as CodingContentTypeEnum
    };
}