/**
 * CodeBlurb API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface MinimalContentResponse { 
    id?: number;
    name?: string;
    contentType?: MinimalContentResponse.ContentTypeEnum;
}
export namespace MinimalContentResponse {
    export type ContentTypeEnum = 'CODING' | 'VIDEO' | 'QUIZ';
    export const ContentTypeEnum = {
        CODING: 'CODING' as ContentTypeEnum,
        VIDEO: 'VIDEO' as ContentTypeEnum,
        QUIZ: 'QUIZ' as ContentTypeEnum
    };
}