/**
 * CodeBlurb API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface TestCaseOutcomeResponse { 
    expected?: string;
    actual?: string;
    outcome?: TestCaseOutcomeResponse.OutcomeEnum;
    hints?: Array<string>;
}
export namespace TestCaseOutcomeResponse {
    export type OutcomeEnum = 'PASSED' | 'FAILED';
    export const OutcomeEnum = {
        PASSED: 'PASSED' as OutcomeEnum,
        FAILED: 'FAILED' as OutcomeEnum
    };
}