/**
 * CodeBlurb API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ContentResponse } from './contentResponse';

export interface VideoContentResponse extends ContentResponse { 
    contentType?: VideoContentResponse.ContentTypeEnum;
    description?: string;
    resourceUrl?: string;
}
export namespace VideoContentResponse {
    export type ContentTypeEnum = 'VIDEO';
    export const ContentTypeEnum = {
        VIDEO: 'VIDEO' as ContentTypeEnum
    };
}