GET http://localhost:8080/content/my-content-bundles/separated
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJkZDVlMzFkZC1mNmQ2LTQzZmEtOGM2Ny02OWM4ODMxZDIzNDYiLCJzdWIiOiJhY2Nlc3N0b2tlbiIsImF1ZCI6InRlc3RVc2VyIiwiaXNzIjoiY29kZWJsdXJiIiwiY3VzdG9tZXJJZCI6MSwiZXhwIjoxNjcxNDg0MTIzfQ.zx0zVjG7zHNpAnDi6WgKgKZskNWaMbqNFbACzc45jg9dX5NE38Rd-Y25d_xAI5rT3weB6R-E206ENx3CeSsu4A