GET http://localhost:8080/content/my-content-bundles
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiIzYzYxMTc3MS1mOTcyLTRmNzgtOWQ2Yy0xNDE4NGJhNTBiNGMiLCJzdWIiOiJhY2Nlc3N0b2tlbiIsImF1ZCI6InRlc3RVc2VyIiwiaXNzIjoiY29kZWJsdXJiIiwiY3VzdG9tZXJJZCI6MSwiZXhwIjoxNjY2MDI5MzAzfQ.6sCLhWApus_V7o-EfxZzi3bSd4qr9rEKcD-Z0LzK54oA4hbZfDuqbKxY2JW3OF6FHUEsk3rA7tsALn4FS8stVw