spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  datasource:
    url: jdbc:postgresql://${CODEBLURB_DB_HOST:localhost}:5432/codeblurb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    generate-ddl: true
management:
  endpoint:
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
codeblurb:
  secret-key: CodeBlurbSecretKey1234
