openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
paths:
  /shopping/add-item/{shoppingCartItem}:
    post:
      tags:
        - Shopping
      operationId: addItemToShoppingCart
      parameters:
        - name: shoppingCartItem
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ShoppingCartResponse'
        "400":
          description: Bad request
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /payments/checkout:
    post:
      tags:
        - Payment
      operationId: pay
      responses:
        "200":
          description: OK
  /content/quiz/solution/{contentId}:
    post:
      tags:
        - Content
      operationId: checkSolutionForQuiz
      parameters:
        - name: contentId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QuizSolutionRequest'
        required: true
      responses:
        "200":
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/QuizSolutionResponse'
  /content/code/solution/{contentId}:
    post:
      tags:
        - Content
      operationId: runSolutionFor
      parameters:
        - name: contentId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          application/json:
            schema:
              type: string
        required: true
      responses:
        "200":
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/CodeSolutionResponse'
  /auth/register:
    post:
      tags:
        - Authentication
      operationId: register
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
        required: true
      responses:
        "200":
          description: OK
  /auth/refresh:
    post:
      tags:
        - Authentication
      operationId: refresh
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshTokenRequest'
        required: true
      responses:
        "200":
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/RefreshTokenResponse'
  /auth/logout:
    post:
      tags:
        - Authentication
      operationId: logout
      responses:
        "200":
          description: OK
  /auth/login:
    post:
      tags:
        - Authentication
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        required: true
      responses:
        "200":
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/LoginResponse'
  /auth/force-logout:
    post:
      tags:
        - Authentication
      operationId: forceLogout
      responses:
        "200":
          description: OK
  /shopping/restore-shopping-cart:
    get:
      tags:
        - Shopping
      operationId: restoreShoppingCart
      responses:
        "200":
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ShoppingCartResponse'
  /shopping/available-shopping-items:
    get:
      tags:
        - Shopping
      operationId: getAvailableShoppingItems
      responses:
        "200":
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/GetAvailableShoppingItemsResponse'
  /payments:
    get:
      tags:
        - Payment
      operationId: getPreviousPayments
      responses:
        "200":
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/PreviousPaymentsResponse'
  /content/my-content-bundles:
    get:
      tags:
        - Content
      operationId: getMyContentBundles
      responses:
        "200":
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/MyContentBundlesResponse'
  /shopping/delete-item/{shoppingCartItem}:
    delete:
      tags:
        - Shopping
      operationId: removeItemFromShoppingCart
      parameters:
        - name: shoppingCartItem
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ShoppingCartResponse'
components:
  schemas:
    ContentBundleResponse:
      type: object
      properties:
        includedContent:
          type: array
          items:
            oneOf:
              - $ref: '#/components/schemas/VideoContentResponse'
              - $ref: '#/components/schemas/QuizContentResponse'
              - $ref: '#/components/schemas/CodingContentResponse'
    ContentResponse:
      type: object
      properties:
        name:
          type: string
    QuizContentResponse:
      allOf:
        - $ref: '#/components/schemas/ContentResponse'
        - type: object
          properties:
            id:
              type: integer
              format: int32
            contentType:
              type: string
              enum:
                - QUIZ
            questions:
              type: array
              items:
                $ref: '#/components/schemas/QuizQuestionResponse'
    QuizQuestionResponse:
      type: object
      properties:
        id:
          type: integer
          format: int32
        question:
          type: string
        answers:
          type: array
          items:
            type: string
        solutionIndex:
          type: integer
          format: int32
    CodingContentResponse:
      allOf:
        - $ref: '#/components/schemas/ContentResponse'
        - type: object
          properties:
            id:
              type: integer
              format: int32
            contentType:
              type: string
              enum:
                - CODING
            description:
              type: string
            codeSkeleton:
              type: array
              items:
                type: string
            codeSnippets:
              type: array
              items:
                type: string
            testCases:
              type: array
              items:
                $ref: '#/components/schemas/TestCaseResponse'
            codingContentType:
              type: string
              enum:
                - SCRATCH
                - DRAG_AND_DROP
                - FILL_THE_GAP
    TestCaseResponse:
      type: object
      properties:
        input:
          type: string
        expectedOutput:
          type: string
    VideoContentResponse:
      allOf:
        - $ref: '#/components/schemas/ContentResponse'
        - type: object
          properties:
            contentType:
              type: string
              enum:
                - VIDEO
            description:
              type: string
            resourceUrl:
              type: string
    ShoppingCartResponse:
      type: object
      properties:
        shoppingItems:
          type: array
          items:
            $ref: '#/components/schemas/ShoppingItemResponse'
    ShoppingItemResponse:
      type: object
      properties:
        title:
          type: string
        price:
          type: number
          format: double
        contentBundle:
          $ref: '#/components/schemas/ContentBundleResponse'
    QuizSolutionRequest:
      type: object
      properties:
        solutions:
          type: object
          additionalProperties:
            type: integer
            format: int32
    IncorrectSolutionsResponse:
      type: object
      properties:
        incorrectQuestionId:
          type: integer
          format: int32
        incorrectSolutionSent:
          type: integer
          format: int32
        correctSolution:
          type: integer
          format: int32
    QuizSolutionResponse:
      type: object
      properties:
        correctAnswerQuestionIds:
          type: array
          items:
            type: integer
            format: int32
        incorrectSolutions:
          type: array
          items:
            $ref: '#/components/schemas/IncorrectSolutionsResponse'
    CodeSolutionResponse:
      type: object
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/TestCaseResultResponse'
        overallResult:
          type: string
          enum:
            - ALL_PASSED
            - TESTCASES_FAILED
    TestCaseResultResponse:
      type: object
      properties:
        expected:
          type: string
        actual:
          type: string
        result:
          type: string
          enum:
            - PASSED
            - FAILED
        hints:
          type: array
          items:
            type: string
    RegisterRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    RefreshTokenRequest:
      type: object
      properties:
        refreshToken:
          type: string
    RefreshTokenResponse:
      type: object
      properties:
        accessToken:
          type: string
        refreshToken:
          type: string
    LoginRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    LoginResponse:
      type: object
      properties:
        accessToken:
          type: string
        refreshToken:
          type: string
    GetAvailableShoppingItemsResponse:
      type: object
      properties:
        shoppingItems:
          type: array
          items:
            $ref: '#/components/schemas/ShoppingItemResponse'
    PaymentResponse:
      type: object
      properties:
        pricePayed:
          type: number
          format: double
        boughtContentBundles:
          type: array
          items:
            $ref: '#/components/schemas/ContentBundleResponse'
    PreviousPaymentsResponse:
      type: object
      properties:
        previousPayments:
          type: array
          items:
            $ref: '#/components/schemas/PaymentResponse'
    MyContentBundlesResponse:
      type: object
      properties:
        contentBundles:
          type: array
          items:
            $ref: '#/components/schemas/ContentBundleResponse'
    ErrorResponse:
      type: object
      properties:
        errorMessage:
          type: string
