name: Flutter Pull Request
on:
  pull_request:
    branches:
      - flutter-main
permissions:
  checks: write
  contents: write
jobs:
  flutter-job:
    name: Run Flutter test and analyzer
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Setup Java env
        uses: actions/setup-java@v1
        with:
          java-version: '11.0'
      - name: Flutter action
        uses: subosito/flutter-action@v2.3.0
        with:
          channel: 'stable'
      - run: flutter --version
      - name: Install dependencies
        run: flutter pub get
      - name: Run Format
        run: flutter format --dry-run --set-exit-if-changed .
      - name: Run Analyzer
        run: flutter analyze .
